name: Build & Release
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build App
        run: dotnet build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: 
            "/bin/"
 
